title: Justin's GitHub
description: a collection of fun programming stuff
github_username: jhlarsen1
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
